Add initial parser.
canonical/sqlair-prototype pull request #10
Opened 2022-07-08 07:34 UTC by fernape

Initial parser for sqlair DSL. Top-down parser with precedence for
disambiguation.

Address most suggestions by @benhoyt from [this PR](https://github.com/canonical/sqlair/pull/8)

 * Use `beginChildren` and `endChildren`.
 * Remove PERIOD and COMMA from input/output/groupedcolumns expressions.
 * Rename confusing variable names (`os`, `l`, etc).
 * Avoid `self` for receiver names.
 * Use `strings.Builder` for efficient printing.
 * Add function to pretty print the AST (needs `go test -v`).
 * Rework comments.
 * Properly format files.

Note:
 * Not using `PassthroughExpression` yet. `IdentityExpression` seems to
   fit the same role.
 * Input and Output expressions might be collapsed into one. The
   structure seems identical except for the initial marker.

2022-07-10 23:53 UTC, benhoyt commented on parse/ast.go
> +	var os bytes.Buffer
For consistency, we should use `var sb strings.Builder` as per above.

2022-07-10 23:53 UTC, benhoyt commented on parse/ast.go
> +	var os bytes.Buffer
Similar here.

2022-07-10 23:53 UTC, benhoyt commented on parse/ast.go
> +		if i != len(gce.Children)-1 {
For consistency, can we please use the same technique for both? Either the `if i > 0` technique before printing, or the `if i != len-1` technique after printing -- it's confusing to have a mix of both techniques.

2022-07-10 23:53 UTC, benhoyt commented on parse/parser.go
> +	infixfn  map[TokenType]InfixFunc
Naming nit: prefer `prefixFn` or `prefixFunc` (i.e., capital letter to separate words).

2022-07-10 23:53 UTC, benhoyt commented on parse/parser.go
> +type InfixFunc func(Expression) Expression
I don't think these should be exported/capitalized, as they're an implementation detail, right?

2022-07-10 23:53 UTC, benhoyt commented on parse/parser.go
> +	p.prefixfn = map[TokenType]PrefixFunc{
It seems to me these could be "constant" global variables, initialized once, rather than initialized each parser -- there's nothing instance-specific about them, so we shouldn't have to build the map every time we create a `Parser`. You probably have to change `PrefixFunc` to take a `*Parser` as an argument, though. You can use [method expressions](https://go.dev/ref/spec#Method_expressions) for this, for example:

```go
type PrefixFunc func(*Parser) Expression

var prefixFuncs = map[TokenType]PrefixFunc{
    IDENT: (*Parser).parseIdent,
    // ...
}
```

2022-07-10 23:53 UTC, benhoyt commented on parse/parser.go
> +type InfixFunc func(Expression) Expression
Actually, this goes for a lot of the implementation details in this package: ideally we should only export the minimum subset needed to parse: a `Parse` function (or `Parser` / `Run` if you prefer) and the returns AST types. Even the lexer is an implementation detail (for example, you could rename it to lowercase `type lexer`). It looks like the token types needs to be exported, though, given they're used in the AST.

Everything we export becomes part of a public API and we're stuck with it, whereas things we don't export we can alter at will.

This can also be achieved using `internal` packages, for example the lexer could be a separate, internal package. But that's probably more than we need here.

2022-07-10 23:53 UTC, benhoyt commented on parse/parser.go
> +		fmt.Println("Empty statement")
Debugging left in? Should this return an error or something instead?

2022-07-10 23:53 UTC, benhoyt commented on parse/parser.go
> +	prefixfunc := p.prefixfn[p.currentToken.Type]
Naming nit: separate words with a capital, so `prefixFunc`.

2022-07-10 23:53 UTC, benhoyt commented on parse/parser.go
> +	for prec_level < p.Precedence(p.peekToken) {
Naming nit: use Go style naming, so `precLevel` (or maybe just `level`).

2022-07-10 23:53 UTC, benhoyt commented on parse/parser.go
> +	return &IdentityExpression{p.currentToken}
Don't these functions need to ensure the token is `IDENT`, `STRING`, and so on?

2022-07-10 23:53 UTC, benhoyt commented on parse/parser.go
> +			g.Children = append(g.Children, p.parseExpression(LOWEST))
Won't this allow too much, for example all commas like `(,,,,,,,)`?

2022-07-10 23:53 UTC, benhoyt commented on parse/parser.go
> +	for p.currentToken.Type != RPAREN {
Will this condition mean we loop forever if there's no `RPAREN`, i.e., `(...` and then EOF?

2022-07-10 23:53 UTC, benhoyt commented on parse/parser.go
> +func (p *Parser) NextToken() {
Similar to above comment re exported names: this is an implementation detail and shouldn't be exported, so `nextToken()`.

2022-07-10 23:53 UTC, benhoyt commented on parse/parser_test.go
> +			},
These tests become quite verbose with everything expanded out like this. I wonder if a `makeToken` test helper function would help here, so we could build a token on one line, something like this:

```go
&IdentityExpression{makeToken(IDENT, "SELECT", 0, 1, 1)},
```

2022-07-10 23:53 UTC, benhoyt commented on parse/parser_test.go
> +func TestParserSimpleInputSource(t *testing.T) {
One thing I'm a bit worried about here is whether we've covered all the cases, or got edge cases or termination conditions incorrect, and so on. I think we probably need a more thorough approach to testing, for example: run a large swath of valid and invalid SQL through it. Not sure where you'd get such a body: we could create our own and build on it, or maybe pull in a list from another library's tests, that sort of thing.

We could also use Go's coverage to ensure we've covered all the cases, and fuzzing to ensure we don't have unintended infinite loops or panics. Go has very good tooling for both of these, so they're easy to set up.

2022-07-10 23:54 UTC, benhoyt commented
Thanks for the updates. Looks like a good start!

2022-07-12 07:33 UTC, fernape commented on parse/ast.go
> +	var os bytes.Buffer
Done

2022-07-12 07:33 UTC, fernape commented on parse/ast.go
> +		if i != len(gce.Children)-1 {
Done. Using pre-check

2022-07-12 07:34 UTC, fernape commented on parse/parser.go
> +type InfixFunc func(Expression) Expression
Unless I missed something, most of these methods should be private now

2022-07-12 07:34 UTC, fernape commented on parse/parser.go
> +	for p.currentToken.Type != RPAREN {
Good catch, thanks. Should be fixed. A test was added.

2022-07-12 07:35 UTC, fernape commented on parse/parser.go
> +	infixfn  map[TokenType]InfixFunc
Done

2022-07-12 07:36 UTC, fernape commented on parse/parser.go
> +			g.Children = append(g.Children, p.parseExpression(LOWEST))
Should be fixed. Test added.

2022-07-12 07:36 UTC, fernape commented on parse/parser_test.go
> +			},
Helper added. Tests are now more readable.

2022-07-12 07:38 UTC, fernape commented on parse/parser_test.go
> +func TestParserSimpleInputSource(t *testing.T) {
Yes, ideally we would have a big corpus of SQL queries with a comprehensive mix of input sources, output targets, etc.

2022-07-25 09:02 UTC, manadart approved these changes
I see what you mean about `PassThroughExpression` being unused. Trying to use it makes the parsing a little more complicated with this operator-precedence approach, so we can go with what we've got here for now.

I'll do a series of follow-ups to this with some sundry things.

Nice job.

2022-07-25 10:07 UTC, niemeyer requested changes
Please don't merge this yet. Let's please do a review pass on it together, Fernando. There are a few details that can be improved, and that will help settling a standard for future work.

2022-07-25 11:03 UTC, niemeyer requested changes
Here are a few early points for us to brainstorm a bit on.

2022-07-25 11:03 UTC, niemeyer commented on internal/parse/parser.go
> +	LOWEST = iota
Per standard Go conventions, Go follows a camel-case style, and we typically see some indication of what the constant is about in its name.

2022-07-25 11:03 UTC, niemeyer commented on internal/parse/parser.go
> +func NewParser(l *lexer) *Parser {
Why was the Lexer made private?  This particular line shows a design problem in doing so: how can we have a public function that takes a private type?

2022-07-25 11:03 UTC, niemeyer commented on internal/parse/parser.go
> +	p.prefixFn = map[TokenType]prefixFunc{
prefixFunc or prefixFn?

2022-07-25 11:03 UTC, niemeyer commented on internal/parse/parser.go
> +	// Token types that has prefixFunc do not care about the
It would be nice to have some more clarity about what this means here, perhaps with some examples. Also, why are these maps instantiated as part of the parser for every instance?  Do we plan to change them per-parser, or are they dynamic for some other reason?

Also, "has" => "have", but perhaps irrelevant if docs will change.

2022-07-25 11:03 UTC, niemeyer commented on internal/parse/parser.go
> +	p.infixFn = map[TokenType]infixFunc{
Same notes as above.

2022-07-25 11:03 UTC, niemeyer commented on internal/parse/parser.go
> +		p.errors = append(p.errors, "Empty statement")
As a standard errors in Go are typically lowercase, as it enables composition of messages such as "cannot do this: something went wrong: boom", etc.

2022-07-25 11:03 UTC, niemeyer commented on internal/parse/parser.go
> +		err = fmt.Errorf(strings.Join(p.errors, "\n"))
This is problematic in two different ways.

The first problem is that it's handling the whole message as a format to be processed. It needs to be either `Errorf("%s", msg)`  or `errors.New(msg)`.

The second issue is that this is not composing well. The end user will get errors like:
```
cannot process whatever: this went wrong
this is not working
this is also wrong
```
We need to do a bit more work here to get a nice message, and we have code for this elsewhere. Ping me and I'll find it for you.

2022-07-25 11:03 UTC, niemeyer commented on internal/parse/parser.go
> +	prefixfunc := p.prefixFn[p.currentToken.Type]
prefixfunc prefixFunc prefixFn.. let's please bikeshed on a call for a moment on a stronger convention that readers and future writers will find easy to adopt.

2022-07-25 11:03 UTC, niemeyer commented on internal/parse/parser.go
> +func (p *Parser) parseExpression(prec_level int) Expression {
precLevel

2022-07-25 11:03 UTC, niemeyer commented on internal/parse/parser.go
> +	name := p.parseExpression(p.precedence(p.currentToken)).(*IdentityExpression)
This is a slightly curious statement, as it means the expression coming out of parseExpression must necessarily be an IdentityExpression or this will panic, but there are no checks before that line to ensure that's the case. If parseExpression never returns anything but IdentityExpression, which would be curious of course, then the type of return can be concrete. If it doesn't, then this should be a `foo, ok :=` kind of construct that ensure the function is being called with appropriate state.

2022-07-25 11:03 UTC, niemeyer commented on internal/parse/parser.go
> +			"Line: %d, column: %d: unexpected '%s', expecting PERIOD",
Error must be lowercased, and the message should be tailored for the person that will be reading the issue. So maybe `... expecting '.'`, instead of the internal const name. As an aside, we can probably also make it a bit more fluid, e.g. `expected %q but got %q at line %d column %d`. Worth noting the `%q` instead of `%s`. This makes Go quote the string for us, handling escaping properly.

2022-07-25 11:03 UTC, niemeyer commented on internal/parse/parser.go
> +	field := p.parseExpression(p.precedence(p.currentToken)).(*IdentityExpression)
Similar concern as earlier above.

2022-07-25 11:03 UTC, niemeyer commented on internal/parse/parser.go
> +	name := p.parseExpression(p.precedence(p.currentToken)).(*IdentityExpression)
Same as earlier here and below. I won't repeat the comment, but given how widespread this is it might be worth talking about it to see if there's an easy pattern we can adopt across the code.

2022-07-25 11:03 UTC, niemeyer commented on internal/parse/parser.go
> +	p.nextToken()
Similar issue here as earlier. There's apparently a pattern established about functions trusting external call sites to define their own internal state. This seems problematic, because it means for every function there's an implied and unspecified rule about what state the world is in so that we can call it, otherwise the parser will panic. This kind of approach does not bode well to future work on this code base, when someone else will be writing code and not know what all the expectations were. Let's please talk about this as well.

2022-07-25 11:03 UTC, niemeyer commented on internal/parse/parser.go
> +			"Line: %d, column: %d: unexpected ')', expecting LITERAL",
Same as earlier note on the error message. There's more below, but I'll stop repeating it. Let's please just do a full pass on the error messages.

2022-07-25 11:03 UTC, niemeyer commented on internal/parse/parser_test.go
> +		assert.Equal(t, reflect.TypeOf(c), reflect.TypeOf(&IdentityExpression{}))
We need to organize these tests as a table so that it's much easier to see what's happening, and also much easier to repeat similar cases, and then improve the number of cases tested. Again, let's please chat about it and I'll present some analogous code as inspiration.

2022-07-25 20:39 UTC, benhoyt commented on internal/parse/parser.go
> +func NewParser(l *lexer) *Parser {
It was my suggestion that we reduce the number of exported things (and the lexer is really an implementation detail). However, @niemeyer is right that we can't have an exported function taking a non-exported type. I think we should just have the parser take a `[]byte` or `string` directly, and it can instantiate the lexer (implementation detail). This would also make usage (including tests) simpler.

Then again, now that these packages are `internal` it's much less concerning to me to have a larger exported surface area.

2026-04-14 05:06 UTC, closed without merging